// Customer API Services - Export all services
export { customerMasterService } from './customerMasterService'
export { accountPurposeService } from './accountPurposeService'
export { investmentMasterService } from './investmentMasterService'
export { businessSegmentService } from './businessSegmentService'
export { businessSubSegmentService } from './businessSubSegmentService'
export { dealTypeService } from './dealTypeService'
export { dealSubtypeService } from './dealSubtypeService'
export { productProgramService } from './productProgramService'
export { beneficiaryService } from './beneficiaryService'
export { documentService } from './documentService'
export { dealSegmentService } from './dealSegmentService'
export { ledgerAccountService } from './ledgerAccountService'
export { countryCodeService } from './countryCodeService'
export { currencyCodeService } from './currencyCodeService'

// Customer API Labels Services - Export all label services
export { customerMasterLabelsService } from './customerMasterLabelsService'
export { accountPurposeLabelsService } from './accountPurposeLabelsService'
export { investmentMasterLabelsService } from './investmentMasterLabelsService'
export { businessSegmentLabelsService } from './businessSegmentLabelsService'
export { businessSubSegmentLabelsService } from './businessSubSegmentLabelsService'
export { dealTypeLabelsService } from './dealTypeLabelsService'
export { dealSubtypeLabelsService } from './dealSubtypeLabelsService'
export { productProgramLabelsService } from './productProgramLabelsService'
export { beneficiaryLabelsService } from './beneficiaryLabelsService'
export { documentLabelsService } from './documentLabelsService'
export { dealSegmentLabelsService } from './dealSegmentLabelsService'
export { ledgerAccountLabelsService } from './ledgerAccountLabelsService'
export { countryCodeLabelsService } from './countryCodeLabelsService'
export { currencyCodeLabelsService } from './currencyCodeLabelsService'
