// Unreconciled Transaction label mapping from UNRECONCILED_TRANSACTION API response
// Maps configId to configValue for easy lookup and usage in components

export const PENDING_TRANSACTION_LABELS = {
  // Core Identifiers
  CDL_UNRECONCILED_TRANSACTION_ID: 'Transaction ID',
  CDL_UNRECONCILED_TRANSACTION_UNRECON_TRANSACTION_ID: 'Unreconciled Transaction ID',
  CDL_UNRECONCILED_TRANSACTION_REFERENCE_NUMBER: 'Transaction Reference Number',
  
  // Amounts
  CDL_UNRECONCILED_TRANSACTION_AMOUNT: 'Transaction Amount',
  CDL_UNRECONCILED_TRANSACTION_TOTAL_AMOUNT: 'Total Transaction Amount',
  
  // Dates & Times
  CDL_UNRECONCILED_TRANSACTION_DATETIME: 'Transaction Date & Time',
  CDL_UNRECONCILED_TRANSACTION_VALUE_DATETIME: 'Value Date & Time',
  CDL_UNRECONCILED_TRANSACTION_POSTED_DATETIME: 'Posted Date & Time',
  CDL_UNRECONCILED_TRANSACTION_PROCESSING_DATETIME: 'Processing Date & Time',
  CDL_UNRECONCILED_TRANSACTION_DISCARDED_DATETIME: 'Discarded Date & Time',
  
  // Descriptions & Remarks
  CDL_UNRECONCILED_TRANSACTION_NARRATION: 'Transaction Narration',
  CDL_UNRECONCILED_TRANSACTION_DESCRIPTION: 'Transaction Description',
  CDL_UNRECONCILED_TRANSACTION_PARTICULAR_1: 'Transaction Particular 1',
  CDL_UNRECONCILED_TRANSACTION_PARTICULAR_2: 'Transaction Particular 2',
  CDL_UNRECONCILED_TRANSACTION_PARTICULAR_REMARK_1: 'Transaction Particular Remark 1',
  CDL_UNRECONCILED_TRANSACTION_PARTICULAR_REMARK_2: 'Transaction Particular Remark 2',
  
  // Flags
  CDL_UNRECONCILED_TRANSACTION_DISCARD_FLAG: 'Discard Flag',
  CDL_UNRECONCILED_TRANSACTION_ALLOCATED_FLAG: 'Allocated Flag',
  CDL_UNRECONCILED_TRANSACTION_UNALLOCATED_CATEGORY_FLAG: 'Unallocated Category Flag',
  CDL_UNRECONCILED_TRANSACTION_CREDITED_TO_ESCROW_FLAG: 'Credited to Escrow Flag',
  CDL_UNRECONCILED_TRANSACTION_TAS_UPDATE_REQUESTED_FLAG: 'TAS Update Requested',
  CDL_UNRECONCILED_TRANSACTION_TAS_UPDATE_APPLIED_FLAG: 'TAS Update Applied',
  
  // Banking & Branch
  CDL_UNRECONCILED_TRANSACTION_CHEQUE_REFERENCE_NUMBER: 'Cheque Reference Number',
  CDL_UNRECONCILED_TRANSACTION_BRANCH_IDENTIFIER_CODE: 'Branch Identifier Code',
  CDL_UNRECONCILED_TRANSACTION_POSTED_BRANCH_IDENTIFIER_CODE: 'Posted Branch Identifier Code',
  CDL_UNRECONCILED_TRANSACTION_CURRENCY_CODE: 'Currency Code',
  
  // Custom Fields
  CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_1: 'Custom Field 1',
  CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_2: 'Custom Field 2',
  CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_3: 'Custom Field 3',
  CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_4: 'Custom Field 4',
  CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_5: 'Custom Field 5',
  
  // Additional Fields
  CDL_UNRECONCILED_TRANSACTION_PRIMARY_UNIT_HOLDER_FULL_NAME: 'Primary Unit Holder Full Name',
  CDL_UNRECONCILED_TRANSACTION_TAS_PAYMENT_STATUS_CODE: 'TAS Payment Status Code',
  CDL_UNRECONCILED_TRANSACTION_CORE_BANKING_RESPONSE_PAYLOAD: 'Core Banking Response Payload',
  CDL_UNRECONCILED_TRANSACTION_PAYMENT_REFERENCE_NUMBER: 'Payment Reference Number',
  CDL_UNRECONCILED_TRANSACTION_SUB_BUCKET_IDENTIFIER: 'Sub Bucket Identifier',
  
  // DTOs
  CDL_UNRECONCILED_TRANSACTION_ESCROW_AGREEMENT_DTO: 'Escrow Agreement',
  CDL_UNRECONCILED_TRANSACTION_BUCKET_TYPE_DTO: 'Bucket Type',
  CDL_UNRECONCILED_TRANSACTION_SUB_BUCKET_TYPE_DTO: 'Sub Bucket Type',
  CDL_UNRECONCILED_TRANSACTION_ESCROW_ACCOUNT_DTO: 'Escrow Account',
  CDL_UNRECONCILED_TRANSACTION_DEPOSIT_MODE_DTO: 'Deposit Mode',
  CDL_UNRECONCILED_TRANSACTION_TASK_STATUS_DTO: 'Task Status',
  
  // Transaction Labels (used in the page - keeping for backward compatibility)
  CDL_TRAN_REFNO: 'Tran Reference',
  CDL_TRAN_DESC: 'Tran Desc',
  CDL_TRAN_AMOUNT: 'Tran Amount',
  CDL_TRAN_DATE: 'Tran Date',
  CDL_TRAN_STATUS: ' Status',
  CDL_TRAN_ACTION: 'Actions',
  CDL_TRAN_NOTES: 'Narration',
  CDL_TRAN_TAS_STATUS: 'TAS Match',
  
  // Payment Plan / Split Amount Labels
  CDL_SPLIT_AMOUNT: 'Split Amount',
  CDL_RECEIVABLE_CATEGORY: 'Receivable Category',
  CDL_RECEIVABLE_SUB_CATEGORY: 'Receivable Sub Category',
  CDL_UNIT_NO_OQOOD_FORMAT: 'Unit no. Oqood Format',
  CDL_DEPOSIT_MODE: 'Deposit Mode',
  CDL_CHEQUE_NUMBER: 'Cheque Number',
}

// Utility function to get label by configId
export const getPendingTransactionLabel = (configId) => {
  return PENDING_TRANSACTION_LABELS[configId] || configId
}

// Utility function to get all labels for a specific category
export const getPendingTransactionLabelsByCategory = (category) => {
  const categories = {
    core: [
      'CDL_UNRECONCILED_TRANSACTION_ID',
      'CDL_UNRECONCILED_TRANSACTION_UNRECON_TRANSACTION_ID',
      'CDL_UNRECONCILED_TRANSACTION_REFERENCE_NUMBER',
    ],
    amounts: [
      'CDL_UNRECONCILED_TRANSACTION_AMOUNT',
      'CDL_UNRECONCILED_TRANSACTION_TOTAL_AMOUNT',
      'CDL_UNRECONCILED_TRANSACTION_CURRENCY_CODE',
    ],
    dates: [
      'CDL_UNRECONCILED_TRANSACTION_DATETIME',
      'CDL_UNRECONCILED_TRANSACTION_VALUE_DATETIME',
      'CDL_UNRECONCILED_TRANSACTION_POSTED_DATETIME',
      'CDL_UNRECONCILED_TRANSACTION_PROCESSING_DATETIME',
      'CDL_UNRECONCILED_TRANSACTION_DISCARDED_DATETIME',
    ],
    remarks: [
      'CDL_UNRECONCILED_TRANSACTION_NARRATION',
      'CDL_UNRECONCILED_TRANSACTION_DESCRIPTION',
      'CDL_UNRECONCILED_TRANSACTION_PARTICULAR_1',
      'CDL_UNRECONCILED_TRANSACTION_PARTICULAR_2',
      'CDL_UNRECONCILED_TRANSACTION_PARTICULAR_REMARK_1',
      'CDL_UNRECONCILED_TRANSACTION_PARTICULAR_REMARK_2',
    ],
    banking: [
      'CDL_UNRECONCILED_TRANSACTION_BRANCH_IDENTIFIER_CODE',
      'CDL_UNRECONCILED_TRANSACTION_POSTED_BRANCH_IDENTIFIER_CODE',
      'CDL_UNRECONCILED_TRANSACTION_CHEQUE_REFERENCE_NUMBER',
      'CDL_UNRECONCILED_TRANSACTION_PRIMARY_UNIT_HOLDER_FULL_NAME',
    ],
    status: [
      'CDL_UNRECONCILED_TRANSACTION_TAS_PAYMENT_STATUS_CODE',
      'CDL_UNRECONCILED_TRANSACTION_ALLOCATED_FLAG',
      'CDL_UNRECONCILED_TRANSACTION_UNALLOCATED_CATEGORY_FLAG',
      'CDL_UNRECONCILED_TRANSACTION_DISCARD_FLAG',
      'CDL_UNRECONCILED_TRANSACTION_CREDITED_TO_ESCROW_FLAG',
      'CDL_UNRECONCILED_TRANSACTION_TAS_UPDATE_REQUESTED_FLAG',
      'CDL_UNRECONCILED_TRANSACTION_TAS_UPDATE_APPLIED_FLAG',
    ],
    custom: [
      'CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_1',
      'CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_2',
      'CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_3',
      'CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_4',
      'CDL_UNRECONCILED_TRANSACTION_CUSTOM_FIELD_5',
    ],
    dtos: [
      'CDL_UNRECONCILED_TRANSACTION_ESCROW_AGREEMENT_DTO',
      'CDL_UNRECONCILED_TRANSACTION_BUCKET_TYPE_DTO',
      'CDL_UNRECONCILED_TRANSACTION_SUB_BUCKET_TYPE_DTO',
      'CDL_UNRECONCILED_TRANSACTION_ESCROW_ACCOUNT_DTO',
      'CDL_UNRECONCILED_TRANSACTION_DEPOSIT_MODE_DTO',
      'CDL_UNRECONCILED_TRANSACTION_TASK_STATUS_DTO',
    ],
  }

  return (
    categories[category]?.map((configId) => ({
      configId,
      label: PENDING_TRANSACTION_LABELS[configId],
    })) || []
  )
}

// Export the full mapping object for direct access
export default PENDING_TRANSACTION_LABELS
