// Processed Transaction (Reconciled Transaction) label mapping
// Maps configId to configValue for fallback when API labels are not available
// This ensures consistent labeling across the application

export const PROCESSED_TRANSACTION_LABELS = {
  // Main Fields
  CDL_RECONCILED_TRANSACTION_ID: 'ID',
  CDL_RECONCILED_TRANSACTION_RECON_TRANSACTION_ID: 'Reconciled Transaction ID',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_AMOUNT: 'Transaction Amount',
  CDL_RECONCILED_TRANSACTION_TOTAL_TRANSACTION_AMOUNT: 'Total Transaction Amount',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_DATETIME: 'Transaction Date & Time',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_NARRATION: 'Transaction Narration',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_DESCRIPTION: 'Transaction Description',
  CDL_RECONCILED_TRANSACTION_PROCESSING_REMARKS: 'Processing Remarks',
  CDL_RECONCILED_TRANSACTION_ALLOCATED_FLAG: 'Allocated Flag',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_PARTICULAR_1: 'Transaction Particular 1',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_PARTICULAR_2: 'Transaction Particular 2',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_PARTICULAR_REMARK_1: 'Transaction Particular Remark 1',
  CDL_RECONCILED_TRANSACTION_TRANSACTION_PARTICULAR_REMARK_2: 'Transaction Particular Remark 2',
  CDL_RECONCILED_TRANSACTION_CHEQUE_REFERENCE_NUMBER: 'Cheque Reference Number',
  CDL_RECONCILED_TRANSACTION_TAS_UPDATE_REQUESTED_FLAG: 'TAS Update Requested',
  CDL_RECONCILED_TRANSACTION_TAS_UPDATE_APPLIED_FLAG: 'TAS Update Applied',
  CDL_RECONCILED_TRANSACTION_TAS_UPDATE_ENABLED_FLAG: 'TAS Update Enabled',
  CDL_RECONCILED_TRANSACTION_UNIT_REFERENCE_NUMBER: 'Unit Reference Number',
  CDL_RECONCILED_TRANSACTION_TAS_PAYMENT_STATUS_CODE: 'TAS Payment Status Code',
  CDL_RECONCILED_TRANSACTION_BATCH_TRANSACTION_ID: 'Batch Transaction ID',
  CDL_RECONCILED_TRANSACTION_RECONCILIATION_RESPONSE_PAYLOAD: 'Reconciliation Response Payload',
  CDL_RECONCILED_TRANSACTION_ROLLBACK_FLAG: 'Rollback Flag',
  CDL_RECONCILED_TRANSACTION_CORE_BANKING_RESPONSE_PAYLOAD: 'Core Banking Response Payload',
  CDL_RECONCILED_TRANSACTION_PAYMENT_REFERENCE_NUMBER: 'Payment Reference Number',
  CDL_RECONCILED_TRANSACTION_SUB_BUCKET_IDENTIFIER: 'Sub Bucket Identifier',
  CDL_RECONCILED_TRANSACTION_ESCROW_AGREEMENT_DTO: 'Escrow Agreement',
  CDL_RECONCILED_TRANSACTION_BUCKET_TYPE_DTO: 'Bucket Type',
  CDL_RECONCILED_TRANSACTION_SUB_BUCKET_TYPE_DTO: 'Sub Bucket Type',
  CDL_RECONCILED_TRANSACTION_DEPOSIT_MODE_DTO: 'Deposit Mode',
  CDL_RECONCILED_TRANSACTION_ESCROW_ACCOUNT_DTO: 'Escrow Account',
  CDL_RECONCILED_TRANSACTION_NON_RECON_TRANSACTION_DTO: 'Non-Reconciled Transaction',
  CDL_RECONCILED_TRANSACTION_TASK_STATUS_DTO: 'Task Status',

  // Legacy labels for backward compatibility (mapped to new labels)
  CDL_TRAN_DATE: 'Transaction Date & Time',
  CDL_TRAN_REFNO: 'Reconciled Transaction ID',
  CDL_TRAN_DESC: 'Transaction Description',
  CDL_TRAN_AMOUNT: 'Transaction Amount',
  CDL_TRAN_NOTES: 'Transaction Narration',
  CDL_TRAN_STATUS: 'Task Status',
  CDL_TRAN_ACTION: 'Action',
  CDL_TRANS_BP_NAME: 'Build Partner Name',
  CDL_TRANS_BP_ID: 'Build Partner ID',
  CDL_TRANS_BP_CIF: 'Build Partner CIF',
  CDL_TRANS_BPA_NAME: 'Build Partner Assets Name',
  CDL_TRANS_BPA_CIF: 'Build Partner Assets CIF',
  CDL_TRANS_BPA_REGULATOR: 'Regulator ID',
  CDL_TRANS_UNIT_HOLDER: 'Unit Reference Number',
  CDL_TRAN_RECEIVABLE_CATEGORY: 'Receivables Category',
  CDL_TRAN_MATCHING_STATUS: 'TAS / CBS Matching Status',
  CDL_TRAN_TOTAL_AMT: 'Total Transaction Amount',
  CDL_TRANS_APPROVAL_STATUS: 'TAS Payment Status Code',
}

// Helper function to get label with fallback
export const getProcessedTransactionLabel = (configId: string): string => {
  return (PROCESSED_TRANSACTION_LABELS as Record<string, string>)[configId] || configId
}

// Helper function to get multiple labels
export const getProcessedTransactionLabels = (
  configIds: string[]
): Record<string, string> => {
  const labels: Record<string, string> = {}
  configIds.forEach((configId) => {
    labels[configId] = getProcessedTransactionLabel(configId)
  })
  return labels
}

// Helper function to check if a configId has a mapping
export const hasProcessedTransactionLabel = (configId: string): boolean => {
  return configId in PROCESSED_TRANSACTION_LABELS
}

// Export all available configIds for reference
export const PROCESSED_TRANSACTION_CONFIG_IDS = Object.keys(
  PROCESSED_TRANSACTION_LABELS
)

// Export labels by category for better organization
export const PROCESSED_TRANSACTION_LABELS_BY_CATEGORY = {
  MAIN: {
    CDL_RECONCILED_TRANSACTION_ID: PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_ID,
    CDL_RECONCILED_TRANSACTION_RECON_TRANSACTION_ID:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_RECON_TRANSACTION_ID,
  },
  TRANSACTION: {
    CDL_RECONCILED_TRANSACTION_TRANSACTION_AMOUNT:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TRANSACTION_AMOUNT,
    CDL_RECONCILED_TRANSACTION_TOTAL_TRANSACTION_AMOUNT:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TOTAL_TRANSACTION_AMOUNT,
    CDL_RECONCILED_TRANSACTION_TRANSACTION_DATETIME:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TRANSACTION_DATETIME,
    CDL_RECONCILED_TRANSACTION_TRANSACTION_NARRATION:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TRANSACTION_NARRATION,
    CDL_RECONCILED_TRANSACTION_TRANSACTION_DESCRIPTION:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TRANSACTION_DESCRIPTION,
  },
  STATUS: {
    CDL_RECONCILED_TRANSACTION_ALLOCATED_FLAG:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_ALLOCATED_FLAG,
    CDL_RECONCILED_TRANSACTION_TAS_UPDATE_REQUESTED_FLAG:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TAS_UPDATE_REQUESTED_FLAG,
    CDL_RECONCILED_TRANSACTION_TAS_UPDATE_APPLIED_FLAG:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TAS_UPDATE_APPLIED_FLAG,
    CDL_RECONCILED_TRANSACTION_TAS_PAYMENT_STATUS_CODE:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TAS_PAYMENT_STATUS_CODE,
    CDL_RECONCILED_TRANSACTION_TASK_STATUS_DTO:
      PROCESSED_TRANSACTION_LABELS.CDL_RECONCILED_TRANSACTION_TASK_STATUS_DTO,
  },
}
